Added guildVanityURLRemove, guildVanityURLUpdate
Androz2091/discord-logs pull request #57
Opened 2021-01-14 14:14 UTC by Mysterinou

2021-01-14 14:21 UTC, Androz2091 commented on handlers/guildUpdate.ts
> +     *   console.log(guild.name+" has remove a vanity url : "+vanityURL);
```suggestion
     *   console.log(guild.name+" has removed its vanity url : "+vanityURL);
```

2021-01-14 14:21 UTC, Androz2091 commented on handlers/guildUpdate.ts
> +     * @param {DJS:Guild} guild The guild which remove a vanity url.
```suggestion
     * @param {DJS:Guild} guild The guild which removed its vanity URL.
```

2021-01-14 14:22 UTC, Androz2091 requested changes

2021-01-14 14:22 UTC, Androz2091 commented on handlers/guildUpdate.ts
> +     * @description Emitted when a guild removes a vanity url.
```suggestion
     * @description Emitted when a guild removes its vanity URL.
```

2021-01-14 14:22 UTC, Androz2091 commented on handlers/guildUpdate.ts
> +     * @param {DJS:Guild} guild The guild which update a vanity url.
```suggestion
     * @param {DJS:Guild} guild The guild which updated a vanity URL.
```

2021-01-14 14:22 UTC, Androz2091 commented on handlers/guildUpdate.ts
> +     * @description Emitted when a guild update a vanity url.
```suggestion
     * @description Emitted when a guild updates its vanity URL.
```

2021-01-14 14:22 UTC, Androz2091 commented on handlers/guildUpdate.ts
> +     * @param {string} vanityURL The vanity url.
```suggestion
     * @param {string} vanityURL The updated vanity URL.
```

2021-01-14 14:23 UTC, Androz2091 requested changes
Merci 👍 
Ce serait bien d'ajouter l'ancienne URL de vanity pour guildVanityURLUpdate

2021-01-15 23:58 UTC, Mysterinou commented
J'ai ajouter l'ancien URL.

2021-01-15 23:59 UTC, Shaynlink approved these changes

2021-01-16 08:54 UTC, Androz2091 requested changes

2021-01-16 08:54 UTC, Androz2091 commented on handlers/guildUpdate.ts
> +     * @param {string} vanityURL The updated vanity URL.
```suggestion
     * @param {DJS:Guild} guild The guild which updated a vanity URL.
     * @param {string} oldVanityURL The former vanity URL.
     * @param {string} vanityURL The updated vanity URL.
```

2021-01-16 08:54 UTC, Androz2091 commented on handlers/guildUpdate.ts
> +     *   console.log(`${guild.name} to change the vanity URL from ${oldGuildvanityURL} to ${newGuildvanityURL} !`);
```suggestion
     *   console.log(`${guild.name} has changed its vanity URL from ${oldGuildvanityURL} to ${newGuildvanityURL} !`);
```

2021-01-16 08:55 UTC, Androz2091 approved these changes
Thank you 👍

2021-01-16 08:55 UTC, merged